/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSubjectsSubjectIdIndexRouteImport } from './routes/_app/subjects/$subjectId/index'
import { Route as AppDecksDeckIdIndexRouteImport } from './routes/_app/decks/$deckId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsSubjectIdIndexRoute =
  AppSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDecksDeckIdIndexRoute = AppDecksDeckIdIndexRouteImport.update({
  id: '/decks/$deckId/',
  path: '/decks/$deckId/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/decks/$deckId/': typeof AppDecksDeckIdIndexRoute
  '/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/decks/$deckId': typeof AppDecksDeckIdIndexRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/decks/$deckId/': typeof AppDecksDeckIdIndexRoute
  '/_app/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/decks/$deckId/'
    | '/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/decks/$deckId' | '/subjects/$subjectId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/decks/$deckId/'
    | '/_app/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subjects/$subjectId/': {
      id: '/_app/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof AppSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/decks/$deckId/': {
      id: '/_app/decks/$deckId/'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId/'
      preLoaderRoute: typeof AppDecksDeckIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDecksDeckIdIndexRoute: typeof AppDecksDeckIdIndexRoute
  AppSubjectsSubjectIdIndexRoute: typeof AppSubjectsSubjectIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDecksDeckIdIndexRoute: AppDecksDeckIdIndexRoute,
  AppSubjectsSubjectIdIndexRoute: AppSubjectsSubjectIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
